version: '3.8'

services:
  aicontent:
    build:
      context: .
      dockerfile: AiContent/Dockerfile
    container_name: aicontent-api
    ports:
      - "5292:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ServiceB__ApiKey=${SECRET_API_KEY}
    networks:
      - k5u1-network
    depends_on:
      - llmproxy

  llmproxy:
    build:
      context: .
      dockerfile: LlmProxy/Dockerfile
    container_name: llmproxy-api
    ports:
      - "5188:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ApiKey=${SECRET_API_KEY}
      - Gemini__ApiKey=${GEMINI_API_KEY}
    networks:
      - k5u1-network

networks:
  k5u1-network:
    driver: bridge
